### ISSUE TITLE
Make the link to the donation page more prominent

### ISSUE THREAD

**Issue by danohart** [danohart/threegreenbirds#3]
Important that this link draws the attention of the website visitor.

**Comment by danohart** [comment]
@threegreenbirds This will be a main focus for me in moving forward with this revamp. Typically, a visitor reads a website top left to top right and then scrolls down, so I think moving the donation page link to be the last menu item could work at getting people's attention. I also have a few thoughts on subtle design ideas that I could do to make it aesthetically pleasing to a visitor.

Let me know if you have any particular thoughts on this topic and post them here so I can take that into consideration.

**Comment by threegreenbirds** [comment]
That all sounds good. We also wondered about highlighting the "Donate" menu item with a slightly different color background, too. Do you think that would work?

**Comment by danohart** [comment]
Yes I do! And that's what I have done here with commit f654f61b3130bffc5a7aa2c89f6f18292a10191b
