### ISSUE TITLE
Copy our existing content and widgets to the new site

### ISSUE THREAD

**Issue by danohart** [danohart/threegreenbirds#5]

**Comment by danohart** [comment]
@threegreenbirds So I have a staging site set up with all your existing content over here 

https://threegreenbirdsorg.mystagingwebsite.com/

Please click around and check it all out. It's very exciting to get a fresh new look. You can also log in by going to https://threegreenbirdsorg.mystagingwebsite.com/wp-login.php and you can use the same credentials as you do on your current website.

Take a look around and please do not hesitate to give any feedback, changes, or edits that should be made. The one thing that I'm going to focus on next is to get some social links into this theme. What are the links to your social media accounts that I should link from the website?

**Comment by threegreenbirds** [comment]
https://www.facebook.com/ThreeGreenBirds
https://twitter.com/ThreeGreenBirds
https://www.instagram.com/ThreeGreenBirds
https://www.youtube.com/user/ThreeGreenBirds

We are also considering opening a Snapchat account - do you think that would help us reach younger people?

**Comment by threegreenbirds** [comment]
Also, it looks like the front page has three broken images on it.

**Comment by danohart** [comment]
Ahh I see that. Those images have been fixed and makes the homepage look more complete :) 

Thank you for the social media links. I'll get those linked up soon.  In regards to snapchat, there does seem to be a younger audience that uses it. If you have a team member that is already using Snapchat regularly, I would see if they would be interested in managing an account on there for your organization. However I am seeing a trend in people not using Snapchat as much, but utilizing Instagram Stories more and more. Something to think about as you move forward and see where you get more engagement in.

**Comment by danohart** [comment]
I also just added some color to the sidebar to draw a little more attention to that information over there, so check it out and tell me what you think https://threegreenbirdsorg.mystagingwebsite.com/ .

**Comment by threegreenbirds** [comment]
Thanks for the advice, we'll skip using Snapchat for now.
