### ISSUE TITLE
Make the site mobile-friendly

### ISSUE THREAD

**Issue by danohart** [danohart/threegreenbirds#6]
Very important.

**Comment by danohart** [comment]
@threegreenbirds This is a passion task of mine. As I love it when a website looks great on a mobile device. Are there any example sites that you like that I could draw inspiration from?

**Comment by threegreenbirds** [comment]
@danohart nothing in particular - we just want it to be a great mobile experience.

**Comment by danohart** [comment]
Implemented with 2bc9b8d8818d8b1de4694273c4f712f11be4612e
