### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by threegreenbirds** [danohart/threegreenbirds#7]
Could you please add Google Analytics tracking code to the footer of our site? We'd like to do this in the WordPress theme itself, without using a plugin, and we'd also like to make sure the code is only displayed when the user is logged out. Here's the analytics code to include:

```
     <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-123456789-1', 'auto');
        ga('send', 'pageview');

      </script>
```

**Comment by danohart** [comment]
Awesome. This code is now implemented and it won't track a user if they're logged in.

**Comment by threegreenbirds** [comment]
Thanks. Could you refactor this to use a function that is hooked into `wp_footer` instead of putting it directly in the footer template?

**Comment by danohart** [comment]
Sure can. This is done here 987bc9f82f0dbf0d2052864b248ba2faedd91eae .
